version: "3.9"
services:
  redis:
    image: redis:6.2.6-alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/var/lib/redis
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - './backend:/app'
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

volumes:
  pg_data:
  redis_data: