# Generated by Django 4.0.2 on 2022-04-23 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaddress",
            name="city",
            field=models.CharField(default="Stara Lubovna", max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="city",
            field=models.CharField(default="Stara Lubovna", max_length=85),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="additional_info",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="additional_info",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="billing_address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="banking.billingaddress",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="children",
            field=models.ManyToManyField(
                related_name="parents",
                through="banking.ChildParent",
                to="banking.UserProfile",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="shipping_address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="banking.shippingaddress",
            ),
        ),
    ]
