# Generated by Django 4.0.2 on 2022-04-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="title",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
